In [4]:
import pandas as pd
import pandas as pd
import numpy as np
from math import radians, sin, cos, sqrt, atan2

In [5]:
df=pd.read_xml(r'D:\Github\ship_data\093 Syrma - AIS Data 1-Jan-24 to 30-Apr-24.xml',parse_dates=["TIMESTAMP"])

In [6]:
df.head()

,MMSI,IMO,STATUS,SPEED,LON,LAT,COURSE,HEADING,TIMESTAMP,SHIP_ID
0,312564000,9218923,5,0,103.8900,1.088333,40,511,2024-01-19 03:16:53,662466
1,312564000,9218923,5,0,103.8900,1.088333,40,77,2024-01-19 03:37:53,662466
2,312564000,9218923,5,0,103.8914,1.089367,40,78,2024-01-19 04:00:48,662466
3,312564000,9218923,5,0,103.8900,1.088333,40,78,2024-01-19 04:22:54,662466
4,312564000,9218923,5,0,103.8913,1.087745,229,317,2024-01-21 04:06:11,662466

In [7]:
df.tail()

,MMSI,IMO,STATUS,SPEED,LON,LAT,COURSE,HEADING,TIMESTAMP,SHIP_ID
19069,533132848,9218923,5,24,101.2966,2.943483,34,31,2024-04-29 23:34:39,662466
19070,533132848,9218923,5,27,101.2974,2.944483,38,119,2024-04-29 23:36:49,662466
19071,533132848,9218923,5,9,101.2983,2.944467,123,133,2024-04-29 23:40:09,662466
19072,533132848,9218923,5,9,101.2988,2.944017,132,118,2024-04-29 23:43:08,662466
19073,533132848,9218923,5,1,101.2992,2.943683,149,122,2024-04-29 23:49:09,662466

In [8]:

df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])


# Function to calculate distance using Haversine formula
def haversine(lat1, lon1, lat2, lon2):
    # Convert latitude and longitude from degrees to radians
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    
    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    
    # Radius of the Earth in kilometers
    R = 6371.0
    
    # Calculate the distance
    distance = R * c
    return distance

# Calculate distance traveled per day
daily_distance = {}
prev_lat, prev_lon = np.nan, np.nan
prev_timestamp = None

for index, row in df.iterrows():
    curr_lat = row['LAT']
    curr_lon = row['LON']
    curr_timestamp = row['TIMESTAMP']
    
    if not pd.isnull(prev_lat) and not pd.isnull(prev_lon):
        # Calculate distance between consecutive points
        dist = haversine(prev_lat, prev_lon, curr_lat, curr_lon)
        
        # Check if it's a new day
        if prev_timestamp.date() != curr_timestamp.date():
            # Store daily distance for the previous day
            if prev_timestamp.date() not in daily_distance:
                daily_distance[prev_timestamp.date()] = 0.0
            daily_distance[prev_timestamp.date()] += dist
        else:
            # Add distance to the current day
            if curr_timestamp.date() not in daily_distance:
                daily_distance[curr_timestamp.date()] = 0.0
            daily_distance[curr_timestamp.date()] += dist
    
    # Update previous values
    prev_lat, prev_lon = curr_lat, curr_lon
    prev_timestamp = curr_timestamp

# Print daily distances
for date, distance in daily_distance.items():
    print(f"Date: {date}, Distance Traveled: {distance:.3f} km")

Date: 2024-01-19, Distance Traveled: 0.546 km
Date: 2024-01-21, Distance Traveled: 0.461 km
Date: 2024-01-22, Distance Traveled: 2.202 km
Date: 2024-01-23, Distance Traveled: 5.074 km
Date: 2024-01-24, Distance Traveled: 4.536 km
Date: 2024-01-25, Distance Traveled: 216.685 km
Date: 2024-01-26, Distance Traveled: 176.281 km
Date: 2024-01-27, Distance Traveled: 30.657 km
Date: 2024-01-28, Distance Traveled: 2.965 km
Date: 2024-01-29, Distance Traveled: 1.256 km
Date: 2024-01-30, Distance Traveled: 0.768 km
Date: 2024-01-31, Distance Traveled: 8.260 km
Date: 2024-02-01, Distance Traveled: 3.599 km
Date: 2024-02-02, Distance Traveled: 16.224 km
Date: 2024-02-03, Distance Traveled: 62.200 km
Date: 2024-02-04, Distance Traveled: 42.420 km
Date: 2024-02-05, Distance Traveled: 40.599 km
Date: 2024-02-06, Distance Traveled: 44.662 km
Date: 2024-02-07, Distance Traveled: 55.416 km
Date: 2024-02-08, Distance Traveled: 59.865 km
Date: 2024-02-09, Distance Traveled: 51.663 km
Date: 2024-02-10, Distance Traveled: 58.897 km
Date: 2024-02-11, Distance Traveled: 28.841 km
Date: 2024-02-12, Distance Traveled: 57.397 km
Date: 2024-02-13, Distance Traveled: 53.567 km
Date: 2024-02-14, Distance Traveled: 58.589 km
Date: 2024-02-15, Distance Traveled: 66.071 km
Date: 2024-02-16, Distance Traveled: 53.864 km
Date: 2024-02-17, Distance Traveled: 46.201 km
Date: 2024-02-18, Distance Traveled: 58.693 km
Date: 2024-02-19, Distance Traveled: 52.083 km
Date: 2024-02-20, Distance Traveled: 54.875 km
Date: 2024-02-21, Distance Traveled: 46.484 km
Date: 2024-02-22, Distance Traveled: 31.299 km
Date: 2024-02-23, Distance Traveled: 55.351 km
Date: 2024-02-24, Distance Traveled: 45.545 km
Date: 2024-02-25, Distance Traveled: 49.339 km
Date: 2024-02-26, Distance Traveled: 42.353 km
Date: 2024-02-27, Distance Traveled: 50.431 km
Date: 2024-02-28, Distance Traveled: 60.237 km
Date: 2024-02-29, Distance Traveled: 37.273 km
Date: 2024-03-01, Distance Traveled: 65.251 km
Date: 2024-03-02, Distance Traveled: 53.974 km
Date: 2024-03-03, Distance Traveled: 47.390 km
Date: 2024-03-04, Distance Traveled: 65.455 km
Date: 2024-03-05, Distance Traveled: 49.800 km
Date: 2024-03-06, Distance Traveled: 16.574 km
Date: 2024-03-08, Distance Traveled: 24.182 km
Date: 2024-03-09, Distance Traveled: 65.413 km
Date: 2024-03-10, Distance Traveled: 53.246 km
Date: 2024-03-11, Distance Traveled: 63.739 km
Date: 2024-03-12, Distance Traveled: 54.157 km
Date: 2024-03-13, Distance Traveled: 39.059 km
Date: 2024-03-14, Distance Traveled: 48.756 km
Date: 2024-03-15, Distance Traveled: 51.692 km
Date: 2024-03-16, Distance Traveled: 60.152 km
Date: 2024-03-17, Distance Traveled: 49.307 km
Date: 2024-03-18, Distance Traveled: 62.244 km
Date: 2024-03-19, Distance Traveled: 52.281 km
Date: 2024-03-20, Distance Traveled: 50.819 km
Date: 2024-03-21, Distance Traveled: 36.780 km
Date: 2024-03-22, Distance Traveled: 69.207 km
Date: 2024-03-23, Distance Traveled: 43.346 km
Date: 2024-03-24, Distance Traveled: 68.559 km
Date: 2024-03-25, Distance Traveled: 39.836 km
Date: 2024-03-26, Distance Traveled: 58.161 km
Date: 2024-03-27, Distance Traveled: 43.689 km
Date: 2024-03-28, Distance Traveled: 52.186 km
Date: 2024-03-29, Distance Traveled: 34.923 km
Date: 2024-03-30, Distance Traveled: 45.825 km
Date: 2024-03-31, Distance Traveled: 49.099 km
Date: 2024-04-01, Distance Traveled: 55.890 km
Date: 2024-04-02, Distance Traveled: 37.033 km
Date: 2024-04-03, Distance Traveled: 44.107 km
Date: 2024-04-04, Distance Traveled: 50.178 km
Date: 2024-04-05, Distance Traveled: 20.260 km
Date: 2024-04-06, Distance Traveled: 45.463 km
Date: 2024-04-07, Distance Traveled: 55.808 km
Date: 2024-04-08, Distance Traveled: 59.549 km
Date: 2024-04-09, Distance Traveled: 50.355 km
Date: 2024-04-10, Distance Traveled: 50.123 km
Date: 2024-04-11, Distance Traveled: 40.592 km
Date: 2024-04-12, Distance Traveled: 38.646 km
Date: 2024-04-13, Distance Traveled: 53.947 km
Date: 2024-04-14, Distance Traveled: 9.565 km
Date: 2024-04-15, Distance Traveled: 1.145 km
Date: 2024-04-16, Distance Traveled: 2.257 km
Date: 2024-04-17, Distance Traveled: 29.781 km
Date: 2024-04-18, Distance Traveled: 3.992 km
Date: 2024-04-19, Distance Traveled: 42.803 km
Date: 2024-04-20, Distance Traveled: 18.086 km
Date: 2024-04-21, Distance Traveled: 3.615 km
Date: 2024-04-22, Distance Traveled: 0.277 km
Date: 2024-04-23, Distance Traveled: 36.617 km
Date: 2024-04-24, Distance Traveled: 45.100 km
Date: 2024-04-25, Distance Traveled: 47.287 km
Date: 2024-04-26, Distance Traveled: 39.757 km
Date: 2024-04-27, Distance Traveled: 28.208 km
Date: 2024-04-28, Distance Traveled: 35.786 km
Date: 2024-04-29, Distance Traveled: 53.540 km

In [43]:
groups = []  # List to store groups
current_group = []  # List to store positions of the current group
in_speed_zero_sequence = False  # Flag to track if in a sequence of SPEED=0

# Iterate through the DataFrame
for index, row in df.iterrows():
    if row['SPEED'] == 0:
        if not in_speed_zero_sequence:
            # Start a new group for SPEED=0 sequence
            if current_group:
                # Store the current group if it's not empty
                groups.append(current_group)
                current_group = []  # Reset current group
            # Add this position to the new group
            current_group.append(row)
            in_speed_zero_sequence = True
        else:
            # Continue adding to the current SPEED=0 sequence
            current_group.append(row)
    else:
        # Found SPEED > 0, end the current group
        if in_speed_zero_sequence:
            # Add this non-zero speed position to the group
            current_group.append(row)
            # Store the completed group
            groups.append(current_group)
            current_group = []  # Reset current group
            in_speed_zero_sequence = False

# Add the last group if it's not empty
if current_group:
    groups.append(current_group)

In [44]:
len(groups)

1643

In [71]:
groups[0]

[MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                       103.89
 LAT                     1.088333
 COURSE                        40
 HEADING                      511
 TIMESTAMP    2024-01-19 03:16:53
 SHIP_ID                   662466
 Name: 0, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                       103.89
 LAT                     1.088333
 COURSE                        40
 HEADING                       77
 TIMESTAMP    2024-01-19 03:37:53
 SHIP_ID                   662466
 Name: 1, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8914
 LAT                     1.089367
 COURSE                        40
 HEADING                       78
 TIMESTAMP    2024-01-19 04:00:48
 SHIP_ID                   662466
 Name: 2, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                       103.89
 LAT                     1.088333
 COURSE                        40
 HEADING                       78
 TIMESTAMP    2024-01-19 04:22:54
 SHIP_ID                   662466
 Name: 3, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087745
 COURSE                       229
 HEADING                      317
 TIMESTAMP    2024-01-21 04:06:11
 SHIP_ID                   662466
 Name: 4, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                      1.08785
 COURSE                        40
 HEADING                      317
 TIMESTAMP    2024-01-21 04:27:11
 SHIP_ID                   662466
 Name: 5, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                      1.08785
 COURSE                        40
 HEADING                      318
 TIMESTAMP    2024-01-21 04:49:19
 SHIP_ID                   662466
 Name: 6, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8914
 LAT                     1.087833
 COURSE                        40
 HEADING                      317
 TIMESTAMP    2024-01-21 05:13:15
 SHIP_ID                   662466
 Name: 7, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                      1.08785
 COURSE                        40
 HEADING                      317
 TIMESTAMP    2024-01-21 05:34:14
 SHIP_ID                   662466
 Name: 8, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087883
 COURSE                        40
 HEADING                      317
 TIMESTAMP    2024-01-21 05:55:15
 SHIP_ID                   662466
 Name: 9, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087817
 COURSE                        40
 HEADING                      319
 TIMESTAMP    2024-01-21 06:16:19
 SHIP_ID                   662466
 Name: 10, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                       103.89
 LAT                     1.086667
 COURSE                        40
 HEADING                      318
 TIMESTAMP    2024-01-21 06:41:19
 SHIP_ID                   662466
 Name: 11, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087867
 COURSE                        40
 HEADING                      317
 TIMESTAMP    2024-01-21 07:04:16
 SHIP_ID                   662466
 Name: 12, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                      1.08785
 COURSE                        40
 HEADING                      318
 TIMESTAMP    2024-01-21 07:25:18
 SHIP_ID                   662466
 Name: 13, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8914
 LAT                     1.087833
 COURSE                        40
 HEADING                      318
 TIMESTAMP    2024-01-21 07:46:25
 SHIP_ID                   662466
 Name: 14, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087883
 COURSE                       142
 HEADING                      318
 TIMESTAMP    2024-01-22 03:40:04
 SHIP_ID                   662466
 Name: 15, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087833
 COURSE                       142
 HEADING                      318
 TIMESTAMP    2024-01-22 04:03:59
 SHIP_ID                   662466
 Name: 16, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                      1.08785
 COURSE                       142
 HEADING                      318
 TIMESTAMP    2024-01-22 04:27:57
 SHIP_ID                   662466
 Name: 17, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                       103.89
 LAT                     1.086667
 COURSE                       302
 HEADING                      317
 TIMESTAMP    2024-01-22 04:50:04
 SHIP_ID                   662466
 Name: 18, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                       103.89
 LAT                     1.086667
 COURSE                       302
 HEADING                      317
 TIMESTAMP    2024-01-22 05:14:03
 SHIP_ID                   662466
 Name: 19, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087833
 COURSE                       315
 HEADING                      317
 TIMESTAMP    2024-01-22 05:37:02
 SHIP_ID                   662466
 Name: 20, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087833
 COURSE                       315
 HEADING                      318
 TIMESTAMP    2024-01-22 05:58:02
 SHIP_ID                   662466
 Name: 21, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087867
 COURSE                       315
 HEADING                      317
 TIMESTAMP    2024-01-22 06:19:01
 SHIP_ID                   662466
 Name: 22, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087833
 COURSE                       315
 HEADING                      317
 TIMESTAMP    2024-01-22 06:46:03
 SHIP_ID                   662466
 Name: 23, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8914
 LAT                     1.087833
 COURSE                       315
 HEADING                      320
 TIMESTAMP    2024-01-22 07:10:04
 SHIP_ID                   662466
 Name: 24, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                       1.0878
 COURSE                       315
 HEADING                      320
 TIMESTAMP    2024-01-22 07:31:01
 SHIP_ID                   662466
 Name: 25, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                       103.89
 LAT                     1.086667
 COURSE                       315
 HEADING                      320
 TIMESTAMP    2024-01-22 07:53:04
 SHIP_ID                   662466
 Name: 26, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8914
 LAT                      1.08775
 COURSE                       315
 HEADING                      320
 TIMESTAMP    2024-01-22 08:16:00
 SHIP_ID                   662466
 Name: 27, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8914
 LAT                     1.087833
 COURSE                       315
 HEADING                      319
 TIMESTAMP    2024-01-22 08:37:14
 SHIP_ID                   662466
 Name: 28, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087817
 COURSE                       315
 HEADING                      319
 TIMESTAMP    2024-01-22 09:05:45
 SHIP_ID                   662466
 Name: 29, dtype: object,
 MMSI                   312564000
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087767
 COURSE                       315
 HEADING                      319
 TIMESTAMP    2024-01-22 09:26:50
 SHIP_ID                   662466
 Name: 30, dtype: object,
 MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087767
 COURSE                       315
 HEADING                      319
 TIMESTAMP    2024-01-22 10:00:22
 SHIP_ID                   662466
 Name: 31, dtype: object,
 MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                      1.08775
 COURSE                       315
 HEADING                      319
 TIMESTAMP    2024-01-22 10:20:50
 SHIP_ID                   662466
 Name: 32, dtype: object,
 MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087767
 COURSE                       315
 HEADING                      319
 TIMESTAMP    2024-01-22 10:44:48
 SHIP_ID                   662466
 Name: 33, dtype: object,
 MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                       103.89
 LAT                     1.086667
 COURSE                       348
 HEADING                      319
 TIMESTAMP    2024-01-22 11:09:55
 SHIP_ID                   662466
 Name: 34, dtype: object,
 MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8914
 LAT                     1.087767
 COURSE                       348
 HEADING                      319
 TIMESTAMP    2024-01-22 11:35:47
 SHIP_ID                   662466
 Name: 35, dtype: object,
 MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8914
 LAT                       1.0878
 COURSE                       348
 HEADING                      318
 TIMESTAMP    2024-01-22 11:56:53
 SHIP_ID                   662466
 Name: 36, dtype: object,
 MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087817
 COURSE                       348
 HEADING                      318
 TIMESTAMP    2024-01-22 12:20:51
 SHIP_ID                   662466
 Name: 37, dtype: object,
 MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          1
 LON                     103.8913
 LAT                     1.087833
 COURSE                       348
 HEADING                      320
 TIMESTAMP    2024-01-22 12:41:49
 SHIP_ID                   662466
 Name: 38, dtype: object]

In [72]:
groups[1]

[MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          0
 LON                     103.8913
 LAT                     1.087833
 COURSE                       348
 HEADING                      319
 TIMESTAMP    2024-01-22 13:08:49
 SHIP_ID                   662466
 Name: 39, dtype: object,
 MMSI                   533132848
 IMO                      9218923
 STATUS                         5
 SPEED                          1
 LON                     103.8913
 LAT                      1.08785
 COURSE                       348
 HEADING                      319
 TIMESTAMP    2024-01-22 13:29:47
 SHIP_ID                   662466
 Name: 40, dtype: object]

In [61]:
data1=groups[10]

In [67]:
pd.to_datetime(data1[0]['TIMESTAMP']),pd.to_datetime(data1[-1]['TIMESTAMP'])

(Timestamp('2024-01-26 11:57:59'), Timestamp('2024-01-26 12:01:21'))

In [68]:
pd.to_datetime(data1[-1]['TIMESTAMP'])-pd.to_datetime(data1[0]['TIMESTAMP'])

Timedelta('0 days 00:03:22')

In [70]:
for group in groups:
    last_timestamp = pd.to_datetime(group[-1]['TIMESTAMP'])
    first_timestamp = pd.to_datetime(group[0]['TIMESTAMP'])
    print(last_timestamp-first_timestamp)

3 days 09:24:56
0 days 00:20:58
0 days 12:48:10
0 days 00:03:01
0 days 05:26:04
1 days 21:17:09
0 days 00:08:03
0 days 00:12:22
0 days 00:06:12
0 days 00:12:11
0 days 00:03:22
0 days 00:12:20
0 days 00:06:13
0 days 00:03:15
0 days 00:15:17
0 days 00:03:05
0 days 00:05:11
0 days 00:06:00
0 days 00:06:06
0 days 00:03:04
0 days 00:04:01
0 days 00:17:45
0 days 00:06:00
0 days 00:03:09
0 days 00:06:00
0 days 00:15:36
0 days 00:18:36
0 days 00:50:25
0 days 01:40:48
0 days 00:42:00
0 days 00:15:01
0 days 00:32:53
0 days 00:27:00
0 days 00:05:56
0 days 00:02:54
0 days 00:44:56
0 days 00:02:51
0 days 00:23:34
0 days 00:04:31
0 days 00:25:38
0 days 00:10:42
0 days 00:07:25
0 days 01:19:40
0 days 01:04:36
0 days 00:07:02
0 days 00:20:44
0 days 04:18:04
0 days 00:20:59
0 days 04:12:18
0 days 04:57:24
0 days 02:11:59
0 days 01:03:00
0 days 00:21:18
0 days 00:24:23
0 days 00:24:05
0 days 01:09:02
0 days 07:09:25
0 days 04:38:56
0 days 00:21:05
0 days 01:24:04
0 days 00:41:59
0 days 00:24:01
0 days 00:21:04
0 days 01:05:59
0 days 00:20:58
0 days 00:21:02
0 days 00:45:05
0 days 09:21:04
0 days 02:15:01
0 days 02:54:01
0 days 01:14:51
0 days 02:14:56
0 days 02:14:59
0 days 04:45:04
0 days 02:30:04
0 days 02:09:01
0 days 00:21:02
0 days 03:27:01
0 days 00:11:55
0 days 01:50:42
0 days 01:05:55
0 days 00:26:11
0 days 01:11:13
0 days 03:20:07
0 days 03:22:25
0 days 03:06:27
0 days 01:57:02
0 days 02:14:41
0 days 01:30:00
0 days 10:12:02
0 days 01:54:03
0 days 01:48:02
0 days 01:53:58
0 days 02:36:06
0 days 00:23:59
0 days 01:03:00
0 days 02:12:03
0 days 00:20:57
0 days 01:51:01
0 days 03:06:20
0 days 02:48:23
0 days 00:44:18
0 days 00:15:07
0 days 00:03:09
0 days 00:29:03
0 days 01:20:01
0 days 00:35:57
0 days 00:10:31
0 days 00:22:30
0 days 00:02:02
0 days 00:51:03
0 days 01:01:53
0 days 00:08:28
0 days 00:11:58
0 days 00:21:42
0 days 01:27:00
0 days 00:24:00
0 days 00:09:02
0 days 00:21:05
0 days 00:27:03
0 days 00:24:01
0 days 02:56:58
0 days 00:18:04
0 days 00:26:44
0 days 00:15:06
0 days 00:23:59
0 days 00:05:15
0 days 00:05:16
0 days 00:15:27
0 days 00:34:07
0 days 00:25:55
0 days 00:13:58
0 days 00:07:53
0 days 00:02:54
0 days 00:03:07
0 days 00:36:04
0 days 00:21:02
0 days 00:20:59
0 days 00:03:22
0 days 00:58:31
0 days 01:37:09
0 days 00:04:06
0 days 03:33:40
0 days 00:50:18
0 days 00:21:22
0 days 00:56:32
0 days 00:20:45
0 days 00:09:52
0 days 00:53:08
0 days 00:50:23
0 days 00:18:01
0 days 00:28:48
0 days 00:09:03
0 days 01:03:55
0 days 00:12:00
0 days 00:11:43
0 days 00:29:08
0 days 00:09:01
0 days 00:29:05
0 days 00:20:55
0 days 00:36:06
0 days 00:02:22
0 days 00:09:57
0 days 00:23:32
0 days 00:09:02
0 days 00:42:12
0 days 00:45:08
0 days 01:51:28
0 days 00:15:03
0 days 00:21:17
0 days 00:05:43
0 days 00:03:01
0 days 00:02:59
0 days 02:14:58
0 days 00:11:12
0 days 00:07:58
0 days 00:24:06
0 days 00:18:11
0 days 00:14:34
0 days 00:32:28
0 days 00:20:10
0 days 00:27:23
0 days 00:31:49
0 days 00:21:05
0 days 01:06:09
0 days 00:13:59
0 days 00:08:57
0 days 00:24:03
0 days 00:09:00
0 days 00:05:56
0 days 00:29:59
0 days 02:03:57
0 days 00:25:05
0 days 01:53:03
0 days 00:53:23
0 days 00:03:01
0 days 00:29:59
0 days 00:18:01
0 days 00:23:58
0 days 00:13:35
0 days 00:24:03
0 days 00:16:50
0 days 00:39:19
0 days 00:12:02
0 days 00:53:11
0 days 00:07:10
0 days 00:12:03
0 days 00:43:38
0 days 00:21:02
0 days 00:42:02
0 days 00:21:02
0 days 00:17:53
0 days 00:02:23
0 days 00:12:35
0 days 00:48:02
0 days 00:04:22
0 days 00:07:27
0 days 00:22:12
0 days 00:09:01
0 days 00:36:02
0 days 00:07:02
0 days 00:25:02
0 days 00:03:01
0 days 00:21:00
0 days 00:41:06
0 days 00:03:40
0 days 00:10:24
0 days 00:08:24
0 days 00:03:07
0 days 00:29:42
0 days 00:02:04
0 days 00:05:01
0 days 01:03:01
0 days 00:17:20
0 days 00:56:37
0 days 00:31:22
0 days 00:14:15
0 days 00:45:27
0 days 00:08:14
0 days 00:48:24
0 days 00:04:04
0 days 00:10:57
0 days 01:03:00
0 days 00:52:33
0 days 00:15:02
0 days 00:05:05
0 days 00:44:14
0 days 01:16:45
0 days 00:02:13
0 days 00:13:10
0 days 00:36:04
0 days 00:05:59
0 days 00:18:24
0 days 00:12:02
0 days 00:26:03
0 days 00:04:14
0 days 00:05:15
0 days 00:08:19
0 days 00:04:17
0 days 00:04:32
0 days 00:17:59
0 days 00:12:44
0 days 00:51:00
0 days 00:12:02
0 days 00:17:58
0 days 02:09:29
0 days 01:08:58
0 days 00:02:13
0 days 01:59:56
0 days 00:32:03
0 days 00:10:05
0 days 00:46:47
0 days 00:12:18
0 days 00:12:42
0 days 00:20:20
0 days 00:06:00
0 days 00:03:00
0 days 00:20:28
0 days 00:18:20
0 days 00:28:17
0 days 00:17:10
0 days 00:02:15
0 days 00:14:56
0 days 00:06:01
0 days 00:08:17
0 days 00:05:59
0 days 00:43:12
0 days 00:42:33
0 days 01:03:01
0 days 00:21:04
0 days 02:31:10
0 days 01:33:04
0 days 01:23:59
0 days 00:02:16
0 days 00:02:07
0 days 01:27:37
0 days 00:12:55
0 days 01:05:24
0 days 00:21:22
0 days 00:03:00
0 days 00:11:01
0 days 00:38:46
0 days 00:06:35
0 days 00:32:12
0 days 00:38:06
0 days 02:38:11
0 days 00:15:07
0 days 00:08:57
0 days 00:11:53
0 days 00:18:07
0 days 00:15:00
0 days 00:13:59
0 days 00:48:13
0 days 01:17:43
0 days 00:08:59
0 days 08:41:15
0 days 00:07:43
0 days 00:25:41
0 days 00:13:36
0 days 00:02:03
0 days 00:02:02
0 days 00:02:28
0 days 00:12:56
0 days 00:29:00
0 days 00:02:39
0 days 00:02:36
0 days 00:03:17
0 days 00:05:31
0 days 00:19:49
0 days 00:26:59
0 days 00:08:00
0 days 00:08:03
0 days 00:02:11
0 days 00:02:59
0 days 00:02:27
0 days 00:52:37
0 days 00:19:43
0 days 00:22:46
0 days 00:10:34
0 days 00:13:36
0 days 00:06:41
0 days 00:04:17
0 days 00:09:00
0 days 01:05:58
0 days 00:17:35
0 days 00:05:58
0 days 00:21:44
0 days 01:00:00
0 days 00:02:57
0 days 00:35:32
0 days 00:23:32
0 days 01:21:27
0 days 00:10:47
0 days 01:06:02
0 days 00:05:57
0 days 00:47:03
0 days 00:42:05
0 days 00:36:22
0 days 00:05:59
0 days 00:05:01
0 days 00:29:57
0 days 00:13:49
0 days 00:06:03
0 days 00:08:58
0 days 00:11:19
0 days 02:24:00
0 days 00:14:59
0 days 00:24:03
0 days 00:40:34
0 days 02:06:02
0 days 00:07:09
0 days 00:18:48
0 days 00:29:03
0 days 01:02:44
0 days 00:27:01
0 days 01:42:21
0 days 00:04:26
0 days 00:04:30
0 days 00:07:14
0 days 01:45:02
0 days 00:05:48
0 days 00:51:12
0 days 00:35:47
0 days 00:03:12
0 days 00:08:50
0 days 00:05:49
0 days 00:17:39
0 days 00:20:29
0 days 00:07:03
0 days 00:06:37
0 days 00:41:29
0 days 01:05:23
0 days 00:15:58
0 days 00:08:57
0 days 00:11:59
0 days 00:03:01
0 days 01:45:03
0 days 00:06:01
0 days 01:51:20
0 days 00:51:56
0 days 00:06:55
0 days 00:23:02
0 days 00:09:08
0 days 00:56:36
0 days 01:02:56
0 days 00:06:01
0 days 00:24:01
0 days 00:45:01
0 days 00:02:59
0 days 00:09:00
0 days 00:02:58
0 days 01:03:00
0 days 00:32:06
0 days 00:07:36
0 days 00:16:04
0 days 00:25:52
0 days 00:06:42
0 days 00:06:05
0 days 00:18:39
0 days 00:02:07
0 days 01:09:54
0 days 00:15:56
0 days 00:02:41
0 days 00:03:41
0 days 00:22:03
0 days 02:23:53
0 days 00:16:32
0 days 02:54:35
0 days 00:18:12
0 days 00:05:07
0 days 00:02:08
0 days 01:05:13
0 days 00:14:55
0 days 00:05:29
0 days 00:02:33
0 days 00:26:24
0 days 00:02:57
0 days 00:03:41
0 days 00:24:46
0 days 00:03:38
0 days 03:05:44
0 days 00:45:05
0 days 01:11:45
0 days 00:14:40
0 days 01:07:48
0 days 00:12:20
0 days 00:23:58
0 days 01:25:06
0 days 00:28:34
0 days 00:48:04
0 days 00:34:06
0 days 00:05:02
0 days 00:23:50
0 days 00:08:28
0 days 00:15:01
0 days 04:07:51
0 days 00:18:02
0 days 01:11:59
0 days 00:05:08
0 days 00:30:08
0 days 00:41:05
0 days 01:11:05
0 days 00:13:59
0 days 00:47:58
0 days 00:15:05
0 days 01:38:33
0 days 00:26:31
0 days 00:24:52
0 days 00:06:03
0 days 00:21:23
0 days 00:04:27
0 days 00:24:12
0 days 00:02:53
0 days 00:03:23
0 days 00:17:58
0 days 00:03:03
0 days 00:02:58
0 days 00:11:16
0 days 00:16:22
0 days 00:21:39
0 days 00:15:00
0 days 00:24:00
0 days 00:07:38
0 days 01:36:11
0 days 00:05:41
0 days 01:39:00
0 days 00:18:00
0 days 00:53:38
0 days 00:31:04
0 days 00:39:43
0 days 00:34:41
0 days 00:32:59
0 days 00:09:19
0 days 01:17:57
0 days 00:25:41
0 days 00:11:55
0 days 00:06:33
0 days 00:21:00
0 days 00:45:06
0 days 01:33:05
0 days 00:34:04
0 days 00:10:01
0 days 00:22:29
0 days 01:25:38
0 days 00:03:08
0 days 00:37:52
0 days 00:17:15
0 days 00:14:58
0 days 00:06:00
0 days 00:26:59
0 days 01:29:50
0 days 00:11:33
0 days 00:08:57
0 days 00:03:19
0 days 00:45:02
0 days 00:21:02
0 days 00:03:57
0 days 00:12:02
0 days 00:03:02
0 days 00:17:58
0 days 00:03:41
0 days 00:05:26
0 days 00:17:10
0 days 00:02:57
0 days 00:05:22
0 days 00:06:00
0 days 00:14:53
0 days 00:26:53
0 days 01:41:29
0 days 00:07:47
0 days 01:02:12
0 days 01:27:05
0 days 00:09:51
0 days 02:44:36
0 days 00:18:10
0 days 04:09:04
0 days 00:06:22
0 days 01:20:00
0 days 01:14:22
0 days 00:02:59
0 days 00:47:54
0 days 00:09:02
0 days 00:09:12
0 days 01:20:46
0 days 00:19:45
0 days 01:33:59
0 days 00:10:03
0 days 00:02:57
0 days 00:23:18
0 days 00:21:37
0 days 00:23:57
0 days 00:15:04
0 days 00:05:30
0 days 00:27:02
0 days 00:03:06
0 days 00:03:12
0 days 00:05:35
0 days 00:39:00
0 days 00:14:57
0 days 00:06:02
0 days 00:17:40
0 days 00:08:58
0 days 00:03:03
0 days 00:26:40
0 days 00:47:37
0 days 00:02:39
0 days 00:21:02
0 days 01:23:46
0 days 02:56:43
0 days 05:25:07
0 days 00:29:09
0 days 01:06:16
0 days 00:30:05
0 days 00:45:00
0 days 00:06:56
0 days 00:03:14
0 days 00:09:13
0 days 00:11:13
0 days 00:05:58
0 days 00:06:00
0 days 00:08:11
0 days 00:31:07
0 days 00:19:04
0 days 00:44:59
0 days 00:09:08
0 days 00:05:36
0 days 00:05:40
0 days 00:02:45
0 days 00:08:45
0 days 00:03:07
0 days 00:20:49
0 days 00:05:57
0 days 00:05:23
0 days 00:34:51
0 days 00:21:07
0 days 00:14:34
0 days 00:15:03
0 days 00:02:16
0 days 00:03:39
0 days 00:14:57
0 days 00:33:36
0 days 00:21:43
0 days 03:40:13
0 days 03:09:32
0 days 01:11:41
0 days 00:04:00
0 days 00:02:33
0 days 02:28:37
0 days 00:03:01
0 days 00:14:09
0 days 00:42:02
0 days 00:09:30
0 days 00:38:55
0 days 01:22:38
0 days 00:23:55
0 days 00:04:49
0 days 00:15:01
0 days 00:26:00
0 days 00:31:57
0 days 00:44:50
0 days 00:02:59
0 days 01:44:58
0 days 01:05:58
0 days 01:02:55
0 days 00:23:56
0 days 00:45:01
0 days 00:03:13
0 days 00:27:00
0 days 00:21:02
0 days 00:42:03
0 days 00:02:58
0 days 00:17:54
0 days 00:12:06
0 days 00:20:59
0 days 00:05:41
0 days 00:05:38
0 days 00:11:43
0 days 00:08:14
0 days 00:06:30
0 days 00:03:58
0 days 01:51:59
0 days 00:03:28
0 days 00:38:08
0 days 00:03:21
0 days 00:13:04
0 days 00:23:57
0 days 00:12:45
0 days 00:46:13
0 days 00:45:01
0 days 00:02:36
0 days 00:05:57
0 days 00:32:16
0 days 00:27:12
0 days 00:03:06
0 days 02:12:09
0 days 00:08:23
0 days 00:50:41
0 days 00:02:06
0 days 02:55:41
0 days 00:26:58
0 days 00:06:07
0 days 00:50:06
0 days 00:05:23
0 days 00:20:56
0 days 00:09:40
0 days 00:04:31
0 days 00:08:01
0 days 00:42:35
0 days 00:42:36
0 days 02:31:45
0 days 00:02:15
0 days 00:42:04
0 days 02:34:15
0 days 00:42:00
0 days 00:24:03
0 days 01:16:50
0 days 00:08:59
0 days 00:02:57
0 days 00:40:26
0 days 00:38:23
0 days 00:20:54
0 days 00:13:06
0 days 00:25:26
0 days 00:04:00
0 days 00:10:56
0 days 00:29:06
0 days 00:34:31
0 days 02:02:05
0 days 00:47:17
0 days 00:59:39
0 days 00:02:36
0 days 00:40:52
0 days 01:54:13
0 days 00:23:58
0 days 02:55:56
0 days 00:54:26
0 days 00:18:25
0 days 00:03:54
0 days 00:13:55
0 days 01:05:22
0 days 00:05:59
0 days 00:53:11
0 days 00:17:31
0 days 00:13:30
0 days 00:13:41
0 days 00:21:58
0 days 00:20:12
0 days 00:06:43
0 days 00:09:43
0 days 01:02:45
0 days 00:03:21
0 days 00:10:06
0 days 01:56:25
0 days 00:11:32
0 days 00:06:22
0 days 00:37:56
0 days 00:41:02
0 days 00:12:31
0 days 00:02:28
0 days 00:57:02
0 days 00:45:10
0 days 00:19:41
0 days 00:06:12
0 days 01:06:29
0 days 00:42:02
0 days 00:19:42
0 days 02:23:02
0 days 00:24:09
0 days 00:04:14
0 days 00:20:57
0 days 00:42:12
0 days 00:11:58
0 days 00:03:03
0 days 00:03:36
0 days 01:14:22
0 days 00:06:02
0 days 00:02:17
0 days 00:19:50
0 days 00:11:01
0 days 00:03:54
0 days 00:04:21
0 days 00:24:01
0 days 00:46:27
0 days 00:13:57
0 days 00:02:19
0 days 00:45:05
0 days 00:28:01
0 days 02:01:14
0 days 00:10:59
0 days 00:02:11
0 days 00:03:14
0 days 02:51:27
0 days 00:03:25
0 days 00:13:22
0 days 00:09:24
0 days 01:00:04
0 days 00:05:16
0 days 00:25:23
0 days 00:17:41
0 days 00:21:08
0 days 00:20:39
0 days 02:34:47
0 days 00:03:00
0 days 00:02:56
0 days 00:20:42
0 days 00:24:24
0 days 00:03:14
0 days 00:03:28
0 days 00:03:31
0 days 00:25:34
0 days 00:11:57
0 days 00:15:26
0 days 00:21:00
0 days 00:02:26
0 days 01:11:57
0 days 01:06:02
0 days 00:32:34
0 days 00:26:38
0 days 00:14:19
0 days 00:05:05
0 days 00:03:13
0 days 00:02:25
0 days 00:06:03
0 days 00:42:03
0 days 00:35:53
0 days 00:25:58
0 days 00:02:14
0 days 00:35:33
0 days 00:15:29
0 days 00:29:05
0 days 00:47:57
0 days 00:04:52
0 days 00:48:56
0 days 00:09:06
0 days 00:02:45
0 days 00:14:07
0 days 00:42:02
0 days 01:02:47
0 days 00:42:07
0 days 00:20:58
0 days 01:32:15
0 days 00:10:02
0 days 00:06:38
0 days 01:07:28
0 days 00:04:06
0 days 00:05:15
0 days 00:03:15
0 days 00:03:47
0 days 00:03:47
0 days 00:08:57
0 days 00:06:01
0 days 00:18:04
0 days 00:13:45
0 days 00:03:39
0 days 01:12:00
0 days 00:53:04
0 days 04:26:52
0 days 00:04:51
0 days 00:21:02
0 days 01:26:57
0 days 01:22:00
0 days 00:25:34
0 days 00:04:52
0 days 00:19:16
0 days 00:12:03
0 days 00:17:01
0 days 00:26:34
0 days 00:05:43
0 days 00:13:22
0 days 00:38:59
0 days 00:15:49
0 days 01:12:00
0 days 00:02:58
0 days 00:08:21
0 days 00:10:39
0 days 00:51:39
0 days 00:11:00
0 days 00:02:44
0 days 00:08:47
0 days 00:38:59
0 days 00:06:00
0 days 00:13:01
0 days 00:14:35
0 days 00:34:44
0 days 00:47:10
0 days 00:02:27
0 days 00:24:00
0 days 00:06:37
0 days 00:06:02
0 days 00:11:21
0 days 01:51:20
0 days 00:24:59
0 days 00:51:01
0 days 00:06:08
0 days 00:03:08
0 days 00:21:53
0 days 00:19:09
0 days 00:21:01
0 days 00:08:18
0 days 00:22:08
0 days 00:13:21
0 days 00:43:14
0 days 01:17:09
0 days 00:02:58
0 days 00:07:31
0 days 00:11:54
0 days 00:21:13
0 days 00:27:14
0 days 00:03:35
0 days 00:03:42
0 days 00:20:59
0 days 00:27:00
0 days 01:24:05
0 days 01:33:00
0 days 00:21:35
0 days 00:43:35
0 days 00:31:55
0 days 00:38:59
0 days 00:24:12
0 days 00:41:20
0 days 00:05:52
0 days 00:24:24
0 days 00:17:57
0 days 00:40:16
0 days 00:05:04
0 days 00:27:36
0 days 00:29:06
0 days 01:53:49
0 days 00:21:52
0 days 00:32:26
0 days 00:16:19
0 days 01:47:49
0 days 00:51:28
0 days 00:25:31
0 days 02:31:23
0 days 00:17:47
0 days 00:48:29
0 days 00:05:23
0 days 00:40:15
0 days 00:21:33
0 days 00:30:23
0 days 00:12:01
0 days 01:12:01
0 days 00:42:06
0 days 02:41:19
0 days 00:09:56
0 days 00:15:20
0 days 00:09:01
0 days 00:35:35
0 days 00:30:55
0 days 00:05:23
0 days 00:51:35
0 days 00:16:25
0 days 00:14:45
0 days 00:00:40
0 days 00:21:30
0 days 00:04:31
0 days 00:03:01
0 days 01:18:45
0 days 00:18:21
0 days 00:29:31
0 days 00:03:48
0 days 00:05:42
0 days 00:06:01
0 days 00:20:58
0 days 00:14:11
0 days 01:29:06
0 days 00:07:31
0 days 00:09:03
0 days 00:54:09
0 days 00:14:55
0 days 02:34:51
0 days 00:18:00
0 days 00:17:08
0 days 01:11:55
0 days 00:02:58
0 days 00:19:40
0 days 00:57:33
0 days 00:30:01
0 days 01:12:03
0 days 00:24:36
0 days 02:15:00
0 days 00:21:22
0 days 00:08:40
0 days 00:06:53
0 days 00:19:57
0 days 00:54:04
0 days 00:54:00
0 days 01:14:01
0 days 00:39:01
0 days 00:41:40
0 days 00:15:01
0 days 01:23:59
0 days 00:03:00
0 days 03:32:58
0 days 00:09:00
0 days 00:51:02
0 days 00:29:59
0 days 02:09:52
0 days 00:06:07
0 days 00:09:02
0 days 00:20:29
0 days 00:13:54
0 days 00:12:56
0 days 00:29:23
0 days 00:10:23
0 days 00:02:24
0 days 00:19:07
0 days 00:24:01
0 days 00:23:14
0 days 00:03:01
0 days 00:02:30
0 days 01:30:06
0 days 00:20:57
0 days 00:14:02
0 days 01:25:39
0 days 00:04:58
0 days 00:08:03
0 days 00:12:00
0 days 00:09:03
0 days 00:02:18
0 days 00:08:20
0 days 01:05:17
0 days 00:02:17
0 days 00:21:10
0 days 00:11:58
0 days 01:06:55
0 days 00:05:06
0 days 00:17:45
0 days 00:20:59
0 days 00:35:17
0 days 00:03:21
0 days 00:06:13
0 days 00:06:06
0 days 00:21:06
0 days 00:08:59
0 days 00:53:58
0 days 00:03:00
0 days 00:03:44
0 days 00:24:02
0 days 00:09:01
0 days 01:06:00
0 days 00:21:00
0 days 00:14:06
0 days 00:12:19
0 days 01:32:26
0 days 01:27:04
0 days 00:20:10
0 days 00:13:26
0 days 00:21:00
0 days 00:15:05
0 days 00:02:28
0 days 00:02:35
0 days 00:45:00
0 days 00:18:03
0 days 00:10:22
0 days 01:47:22
0 days 00:04:03
0 days 00:04:56
0 days 00:17:12
0 days 00:07:04
0 days 00:21:00
0 days 00:02:09
0 days 00:47:56
0 days 00:03:31
0 days 01:17:33
0 days 00:09:00
0 days 00:07:51
0 days 01:10:24
0 days 00:22:12
0 days 00:13:13
0 days 00:09:03
0 days 00:29:58
0 days 00:03:58
0 days 00:06:02
0 days 00:03:00
0 days 00:12:08
0 days 00:47:59
0 days 00:02:56
0 days 00:08:40
0 days 00:19:00
0 days 01:08:56
0 days 00:06:01
0 days 00:41:59
0 days 00:51:02
0 days 00:24:00
0 days 00:05:41
0 days 00:16:40
0 days 00:21:00
0 days 01:00:02
0 days 00:04:42
0 days 00:42:03
0 days 00:02:56
0 days 00:21:36
0 days 00:08:59
0 days 00:06:04
0 days 00:38:58
0 days 00:20:57
0 days 00:20:14
0 days 00:26:06
0 days 00:02:39
0 days 00:05:42
0 days 01:18:02
0 days 00:03:38
0 days 00:10:46
0 days 00:10:35
0 days 00:13:09
0 days 00:21:02
0 days 00:41:54
0 days 01:28:05
0 days 00:41:59
0 days 00:40:57
0 days 00:11:57
0 days 00:02:39
0 days 00:05:42
0 days 00:06:00
0 days 00:02:58
0 days 00:03:07
0 days 00:09:36
0 days 00:21:34
0 days 01:54:56
0 days 00:20:37
0 days 00:12:00
0 days 00:05:57
0 days 00:12:23
0 days 00:12:46
0 days 00:08:55
0 days 00:14:58
0 days 00:19:58
0 days 00:21:01
0 days 10:25:45
0 days 01:36:00
0 days 00:04:29
0 days 00:02:52
0 days 00:24:46
0 days 00:14:31
0 days 00:21:00
0 days 00:58:04
0 days 00:15:22
0 days 00:15:09
0 days 00:24:00
0 days 00:03:43
0 days 00:27:28
0 days 00:20:02
0 days 02:24:25
0 days 00:02:56
0 days 00:04:32
0 days 00:06:16
0 days 00:38:21
0 days 00:38:52
0 days 00:06:00
0 days 00:02:40
0 days 00:18:07
0 days 00:06:29
0 days 02:58:28
0 days 00:15:21
0 days 01:29:43
0 days 00:27:28
0 days 04:53:57
0 days 02:11:49
0 days 00:28:45
0 days 00:03:03
0 days 00:09:43
0 days 00:06:47
0 days 00:06:00
0 days 00:19:10
0 days 00:10:48
0 days 00:24:09
0 days 00:03:36
0 days 00:05:29
0 days 00:44:31
0 days 00:27:23
0 days 00:09:15
0 days 00:23:49
0 days 00:17:35
0 days 00:04:00
0 days 00:42:11
0 days 00:34:24
0 days 00:39:06
0 days 00:11:56
0 days 00:03:37
0 days 00:04:55
0 days 00:02:04
0 days 00:14:58
0 days 00:51:35
0 days 00:26:04
0 days 00:08:00
0 days 00:02:36
0 days 00:06:35
0 days 00:05:54
0 days 00:20:58
0 days 00:02:27
0 days 00:22:30
0 days 00:03:56
0 days 01:46:01
0 days 00:03:49
0 days 00:09:34
0 days 00:04:09
0 days 00:13:01
0 days 00:20:59
0 days 00:32:46
0 days 00:11:07
0 days 00:13:39
0 days 00:06:05
0 days 00:27:22
0 days 00:29:57
0 days 00:46:46
0 days 00:04:19
0 days 00:06:44
0 days 00:06:02
0 days 04:42:08
0 days 01:26:19
0 days 01:32:46
0 days 00:46:34
0 days 00:04:34
0 days 00:02:22
0 days 01:44:58
0 days 00:05:57
0 days 00:02:57
0 days 00:02:02
0 days 01:50:49
0 days 01:54:05
0 days 00:02:18
0 days 00:05:07
0 days 00:05:06
0 days 00:26:24
0 days 00:10:57
0 days 00:26:59
0 days 00:39:05
0 days 01:06:33
0 days 00:12:41
0 days 01:23:59
0 days 00:06:02
0 days 00:18:07
0 days 02:59:08
0 days 00:10:27
0 days 01:11:17
0 days 00:07:15
0 days 01:21:16
0 days 00:18:13
0 days 00:06:27
0 days 00:50:26
0 days 00:10:13
0 days 00:47:21
0 days 00:02:19
0 days 00:37:48
0 days 00:02:28
0 days 00:09:27
0 days 00:15:19
0 days 00:22:10
0 days 00:04:07
0 days 00:06:08
0 days 01:57:47
0 days 00:18:34
0 days 00:44:38
0 days 00:06:23
0 days 00:42:04
0 days 02:52:58
0 days 00:05:20
0 days 00:04:40
0 days 00:41:27
0 days 01:09:26
0 days 01:06:00
0 days 00:49:19
0 days 00:14:26
0 days 00:05:30
0 days 00:11:18
0 days 00:08:26
0 days 00:03:02
0 days 01:53:57
0 days 00:20:39
0 days 00:02:49
0 days 00:48:01
0 days 00:21:12
0 days 00:02:22
0 days 01:01:52
0 days 00:03:47
0 days 00:23:25
0 days 00:21:02
0 days 01:11:59
0 days 01:02:14
0 days 02:09:26
0 days 00:07:22
0 days 02:00:00
0 days 01:02:55
0 days 00:44:05
0 days 00:42:40
0 days 00:03:52
0 days 00:03:55
0 days 00:02:37